window.__translations__ = {
  "hero": {
    "title": "AI Course",
    "subtitle": "A practical guide to artificial intelligence and machine learning"
  },
  "curriculum": {
    "heading": "Curriculum",
    "part0": {
      "label": "Intro",
      "title": "What Can AI Do?",
      "session0": "Introductory lecture: ML and AI agents",
      "session0_content": "Through the analysis of a real-world FinTech system for loan application processing, participants trace the evolution of information systems—from classic digitalization, through the integration of AI services, to the introduction of intelligent agents. The lecture focuses on the specific problems that artificial intelligence solves, providing a clear motivation for introducing each individual technique. The first section analyzes traditional web systems, mapping out the processes where employees are still forced to manually perform reasoning tasks and process unstructured data. The second section introduces AI services (such as computer vision, machine learning, and LLMs) to automate specific tasks, explaining their advantages as well as their limitations regarding business process rigidity. The third section presents the transition to systems based on intelligent agents and orchestrators that manage the process flow declaratively. By positioning AI tools within the continuum of digitalization, participants gain a broader perspective and a solid conceptual framework for understanding advanced techniques in the remainder of the course."
    },
    "part1": {
      "label": "Module 1",
      "title": "What AI Is?",
      "session1": "Learning from data: Introduction to AI and machine learning",
      "session1_content": "Through simple analogies from everyday life, such as fruit recognition, children's games, and cooking, attendees learn basic concepts and principles without complex programming. The lecture is divided into three key sections. The first section explains what machine learning is, its definition, and the difference compared to traditional programming. The second section provides an overview of the types of machine learning, covering supervised, unsupervised, and reinforcement learning in detail, along with an interactive quiz to check knowledge. The third section describes the workflow of a project, guiding attendees through all phases of ML model development—from defining the problem, through data collection and cleaning, all the way to training and evaluation using a practical example of a movie recommendation system.",
      "session2": "Working with tabular data: prediction models",
      "session2_content": "In this lesson, participants are introduced to the practical process of applying machine learning and the methodology of working with real-world datasets, viewed through the lens of engineering practice in the Python programming language. The lecture covers the exploratory data analysis phase, utilizing the Pandas library to load structured tables from remote sources, inspect table structures, and interpret descriptive statistics parameters to understand data distribution and value ranges. The step of data transformation and feature engineering is analyzed in detail, focusing on domain-specific data adaptation through the conversion of surface area measurement units and the preparation of data into the appropriate matrix format of multidimensional arrays. The course also encompasses the modeling process within the Scikit-learn library—from isolating dependent and independent variables, through instantiating a linear regression object, to launching the model training process—culminating in a practical introduction to predicting real estate prices based on square footage.",
      "session3": "AI-driven reasoning: Neural networks",
      "session3_content": "Participants are introduced to the fundamentals of deep learning and the mathematical concepts behind model training, viewed through intuitive analogies and engineering practice. The lecture covers the geometric interpretation of linear functions and the role of derivatives as indicators of the direction and intensity of error correction, explaining how they are used to adjust weights and biases. The anatomy of an artificial neuron and the architecture of the Multilayer Perceptron (MLP) are analyzed in detail, focusing on forward propagation, backward propagation, and parameter optimization via gradient descent. The course also covers key hyperparameters and practical challenges, ranging from loss functions, epochs, and batch sizes, to the analysis of activation functions (ReLU, Sigmoid, Tanh, Softmax), and techniques for addressing vanishing and exploding gradients, culminating in a practical implementation of MNIST dataset classification using the Keras framework.",
      "session4": "Generating and interpreting natural language using AI: LLMs",
      "session4_content": "Participants are introduced to the architecture and working principles of Large Language Models (LLMs), viewed through the lens of engineering practice and natural language processing mechanisms. The lecture covers the concept of autoregressive text generation, explaining how the model predicts the next token through the process of tokenization and vocabulary probability distribution, and how the temperature parameter controls the stochasticity of the response. The Transformer architecture is analyzed in detail through the steps of creating semantic embeddings and positional encoding, with a specific focus on the Self-Attention mechanism and the interaction between query, key, and value vectors during token contextualization. The course also encompasses the internal dynamics of the Transformer block—from expanding dimensionality within the feed-forward network and stabilization through residual connections and normalization, to mapping output vectors into concrete probability distributions—concluding the lesson with an analysis of inherent model limitations such as the context window and the nature of knowledge storage within network weights.",
      "session5": "Handling visual information: Applied computer vision",
      "session5_content": "In this lesson, participants are introduced to the field of computer vision as a branch of artificial intelligence. The lecture covers the fundamental concepts and practical applications of computer vision, such as object recognition and classification, detection of shapes, colors, textures, and motion, as well as motion analysis and scene structure understanding. The process of loading images from storage, along with their inspection and display within the development environment, is analyzed in detail, laying the groundwork for more advanced segmentation techniques and matrix-based image processing covered in the second module.",
      "session6": "From content to actions: AI-driven architectures and agents",
      "session6_content": "Students are introduced to the role and integration of AI models within the architectures of real-world, production applications. The lecture covers the process of embedding a trained model into a web service and the mechanisms for accessing its functionalities via a REST API. The challenges of asynchronous access in high-load systems are analyzed in detail, alongside the necessity of introducing message queues for secure and reliable inter-service communication, with a specific focus on orchestrating multiple isolated AI services into complex business workflows. The session concludes with a transition to the concept of intelligent agents capable of perception, learning, reasoning, and taking action within an environment, explaining how they autonomously monitor events in message-queue-modeled environments and represent the next evolutionary phase of AI services featuring dynamic and flexible workflow execution.",
      "session7": "Putting AI solutions in production: ML ops and administrative issues",
      "session7_content": "Students are introduced to the performance characteristics of AI models and the challenges of deploying them into production environments, considering that these systems are inherently more computationally intensive than traditional web applications. The lecture covers the analysis of hardware and software requirements, clearly differentiating between the resources needed during the intensive model training phase and those required for inference and production deployment. The process of packaging models and their dependencies into Docker containers is analyzed in detail, ensuring the isolation, portability, and scalability of the solutions. The session concludes with linking MLOps technologies to the concepts of asynchronous workflows and agent architectures from the previous lecture, providing students with a comprehensive understanding of the stable operation of intelligent systems."
    },
    "part2": {
      "label": "Module 2",
      "title": "How AI Works?",
      "session8": "Exploratory data analysis",
      "session8_content": "Students are introduced to the critical phases of raw data preparation, cleaning, and transformation into a form suitable for machine learning algorithms. The lecture covers the methodology for handling missing values through imputation or elimination strategies, alongside the identification and treatment of extreme deviations, or outliers, within a dataset. The process of encoding categorical variables using Label and One-Hot methods is analyzed in detail, along with the normalization and scaling of numerical features to standardize value ranges. The session concludes with an understanding of the 'Garbage in, garbage out' principle by analyzing the impact of clean data on model accuracy, training speed, and the prevention of systematic bias, rounded off by interactively resolving real-world anomalies using examples from the automotive sales and real estate market domains.",
      "session9": "Predictive AI models in practice",
      "session9_content": "Students are introduced to the process of practical analysis, modeling, and evaluation of project tasks that rely on predictive AI models to solve regression and classification problems. The lecture covers the detailed decomposition of each individual project problem, the architectural mapping of potential solutions, and critical discussions on engineering challenges and anomalies in practice. The quantitative performance of pre-implemented models is analyzed in detail, where a comparative evaluation of different approaches serves as the basis for selecting the most adequate solution for specific domain requirements. The session concludes with the practical application of evaluation principles and performance metrics, enabling students to develop an intuition for optimization and architectural decision-making when selecting models through the analysis of ready-made solutions.",
      "session10": "Utilizing computer vision models",
      "session10_content": "This session is dedicated to the analysis, design, and implementation of solutions in the domain of computer vision through the analysis of real-world project tasks. The lecture covers the detailed decomposition of complex visual problems and the identification of individual solution components, such as segmentation, object detection, or image classification. The process of selecting optimal models and planning the overall system architecture is analyzed in detail, taking into account the specific requirements of real-time visual information processing. The session concludes with a critical discussion on the performance of pre-implemented solutions, enabling students to make optimal decisions for balancing accuracy and computational intensity by comparing different architectural approaches.",
      "session11": "Using Large Language models",
      "session11_content": "Students are introduced to the methodology and practical techniques for integrating large language models into modern web applications. The lecture covers methods by which specific domain knowledge can be successfully incorporated into systems using architectures such as RAG and protocols like MCP. The mechanisms for managing and handling model performance and behavior through the configuration of its hyperparameters are analyzed in detail, such as controlling stochasticity and response creativity via the temperature parameter. The session concludes with a practical demonstration and architectural analysis of a Q&A chatbot specialized in answering questions from a closed and restricted data domain, providing students with a clear engineering blueprint for developing advanced NLP solutions.",
      "session12": "Building AI agents",
      "session12_content": "Students are introduced to the concepts and architecture of multi-agent systems as advanced solutions for automating complex engineering problems. The lecture covers a detailed analysis of the classes of problems that require an agentic approach, explaining how atomic operations are successfully implemented through external tools and the manner in which a model autonomously selects tools based on the context of the task. The transformation of static elements of workflow execution into a dynamic and adaptive business process is analyzed in detail, which is achieved through a structural division into Manager and Worker agents working in a coordinated and collaborative manner. The session concludes with a practical illustration and analysis of using multi-agent architectures on realistic examples of complex business processes, providing students with clear insights into designing autonomous software ecosystems.",
      "session13": "Kick-starting \"grand slam project candidates\"",
      "session13_content": "Students enter a key phase of the course through collaborative ideation, analysis, and selection of Grand Slam projects. The lecture covers the detailed decomposition of complex project problems into smaller subproblems, the resolution of which is achieved through the application of specific AI techniques and models. Each proposed project candidate is analyzed in detail from the standpoint of selecting adequate algorithmic approaches, resource optimization, and planning potential architectural solutions. The session concludes with a critical evaluation of the feasibility and engineering justification of all proposals, forming the basis for the final selection of the most adequate projects that the students will implement.",
      "session14": "Setting up solution and AI architecture for \"grand slam project candidates\"",
      "session14_content": "Students begin the final phase of the course's practical realization by laying the foundations of their final solutions. The lecture covers the operationalization of the theoretical and architectural conclusions reached during the previous session, transforming concepts into concrete engineering blueprints. The process of initial setup and configuration of the overall system AI architecture is analyzed in detail, defining the connections between models, databases, and the application interface. The session concludes with launching and initializing the implementation of the selected projects, where students, with mentorship support, begin writing production-ready code and establishing their first operational prototypes."
    }
  },
  "contact": {
    "heading": "Contact",
    "infoTitle": "Get in touch",
    "infoDesc": "Have questions about the course? Feel free to contact us via the form or directly.",
    "partner": "In collaboration with FTN Novi Sad",
    "form": {
      "name": "Full name",
      "namePlaceholder": "Your full name",
      "email": "Email address",
      "company": "Company",
      "companyPlaceholder": "Company name (optional)",
      "message": "Message",
      "messagePlaceholder": "Your message or question...",
      "submit": "Send application"
    }
  },
  "cta": {
    "label": "Investment in your career",
    "amount": "1000",
    "currency": " EUR",
    "note": "Participants use their own laptops for practical exercises",
    "button": "Apply today"
  },
  "courseSetup": {
  "heading": "Course Organization",
    "cards": {
      "what":    { "title": "What is the course", "body": "The course covers AI and ML concepts that are becoming indispensable in solving software problems. The goal is to gain an understanding of AI concepts and adopt techniques for their use so you can integrate AI into information systems and problem-solving." },
      "who":     { "title": "Who is the course for", "body": "For people who work in software development but are not familiar with AI, ML, and have not built software solutions based on artificial intelligence." },
      "notWhat": { "title": "What the course is not", "body": "This is not a course on using AI tools for faster development. The focus is on understanding and implementing AI solutions." },
      "notWho":  { "title": "Who it is not for", "body": "For those who already know ML algorithms and use ML models, RAG, agents, and LLMs in their solutions. The course is designed for beginners in the AI domain who want to build solid foundations." }
    },
    "p1": "The course consists of 15 sessions held in the evening, with the workload and commitment fully tailored to employed participants. The course lasts for 2 months. Each session lasts 3 hours, and since the work is highly practical, participants are required to bring their own laptops to class.",
    "p2": "The first, introductory session provides a clear insight into the application of artificial intelligence in production-ready software and tracks the evolution and implementation of AI techniques through a real-world FinTech application example. The remaining sessions are split into two specialized modules.",
    "p3": "The first module is designed for participants to acquire a deep and intuitive understanding of the problems solved by artificial intelligence, as well as the techniques utilized in the process. During this section, all significant theoretical aspects and mathematical foundations of modern AI models are discussed in detail.",
    "p4": "The second module covers the direct application of artificial intelligence techniques in real-world software solutions. In this module, the emphasis is placed on engineering practice—modeling AI services and successfully incorporating them into stable, production environments.",
    "p5": "The total price of the course is 1500 Euros."
  },
  "about": {
    "heading": "About Us",
    "p1": "We are Sokraft, a software company from Novi Sad, founded and led by professors from the Faculty of Technical Sciences. We have been working in the field of artificial intelligence since 2009, a track record backed by over 50 scientific papers we have published in the AI domain. Alongside our academic careers, we are actively engaged in commercial software development, having successfully participated in the realization of over 30 commercial projects, a large portion of which involves AI. Between 2015 and 2022, through our educational company Aleph, we organized web programming courses. Hundreds of participants passed through our workshops and successfully launched their careers, securing jobs in the IT sector. Back then, it was the golden age of web programming, and without a solid grasp of web technologies, serious development was virtually impossible. Today, we find ourselves at a similar historical crossroads: we are witnessing that practically all modern projects require operational knowledge of artificial intelligence. Once again, there is a massive gap in the market: although AI is bringing fundamental changes, there are currently no comprehensive courses that properly cover both the theoretical foundations and the real-world practical applications of modern AI to enable participants to productively join new projects. We created this course with the goal of directly addressing the challenge of the shortage of qualified AI engineers, passing on knowledge that bridges the rigor of academic research and hands-on engineering practice.",
    "p2": "The course is strictly intended for participants who already have prior programming experience. It is designed as an intensive engineering program built to elevate your existing development skills to the level required for building modern AI architectures and autonomous systems."  
  }
};
